# Generated by Django 4.1.1 on 2023-04-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField(max_length=250)),
                ('video_link', models.URLField(max_length=360)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
